/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package NewGUI;

/**
 *
 * @author dodan_000
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btunStatistics = new javax.swing.JButton();
        btnCategory = new javax.swing.JButton();
        btnProject = new javax.swing.JButton();
        btnAccount = new javax.swing.JButton();
        btuAddTransaction = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAccountsSummary = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(890, 560));
        setMinimumSize(new java.awt.Dimension(890, 560));
        setPreferredSize(new java.awt.Dimension(890, 560));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 60));
        jPanel1.setMinimumSize(new java.awt.Dimension(890, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(890, 60));
        jPanel1.setLayout(null);

        btunStatistics.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btunStatistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/main/barChart 24.png"))); // NOI18N
        btunStatistics.setText("Statistics");
        btunStatistics.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btunStatistics.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btunStatistics.setMaximumSize(new java.awt.Dimension(60, 60));
        btunStatistics.setMinimumSize(new java.awt.Dimension(60, 60));
        btunStatistics.setPreferredSize(new java.awt.Dimension(60, 60));
        btunStatistics.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btunStatistics.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btunStatistics);
        btunStatistics.setBounds(80, 0, 80, 60);

        btnCategory.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/main/category 24.png"))); // NOI18N
        btnCategory.setText("Category");
        btnCategory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCategory.setMaximumSize(new java.awt.Dimension(60, 60));
        btnCategory.setMinimumSize(new java.awt.Dimension(60, 60));
        btnCategory.setPreferredSize(new java.awt.Dimension(60, 60));
        btnCategory.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCategory.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btnCategory);
        btnCategory.setBounds(240, 0, 90, 60);

        btnProject.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/main/add project 24.png"))); // NOI18N
        btnProject.setText("Project");
        btnProject.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProject.setMaximumSize(new java.awt.Dimension(60, 60));
        btnProject.setMinimumSize(new java.awt.Dimension(60, 60));
        btnProject.setPreferredSize(new java.awt.Dimension(60, 60));
        btnProject.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnProject.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjectActionPerformed(evt);
            }
        });
        jPanel1.add(btnProject);
        btnProject.setBounds(330, 0, 80, 60);

        btnAccount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/main/account 24.png"))); // NOI18N
        btnAccount.setText("Account");
        btnAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAccount.setMaximumSize(new java.awt.Dimension(60, 60));
        btnAccount.setMinimumSize(new java.awt.Dimension(60, 60));
        btnAccount.setPreferredSize(new java.awt.Dimension(60, 60));
        btnAccount.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAccount.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btnAccount);
        btnAccount.setBounds(160, 0, 78, 60);

        btuAddTransaction.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btuAddTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/main/add-24.png"))); // NOI18N
        btuAddTransaction.setText("Add");
        btuAddTransaction.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btuAddTransaction.setMaximumSize(new java.awt.Dimension(60, 60));
        btuAddTransaction.setMinimumSize(new java.awt.Dimension(60, 60));
        btuAddTransaction.setPreferredSize(new java.awt.Dimension(60, 60));
        btuAddTransaction.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btuAddTransaction.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btuAddTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btuAddTransactionActionPerformed(evt);
            }
        });
        jPanel1.add(btuAddTransaction);
        btuAddTransaction.setBounds(0, 0, 78, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Accounts summary");

        tbAccountsSummary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Account", "Income", "Expense", "Budget"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbAccountsSummary);

        jLabel2.setText("Message");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 268, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProjectActionPerformed
   
    AddTransaction addTransaction = null;
    private void btuAddTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btuAddTransactionActionPerformed
        // TODO add your handling code here:
        
        addTransaction = new AddTransaction();
        addTransaction.setVisible(true);   
    }//GEN-LAST:event_btuAddTransactionActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
 
        
    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        try{
        if(!addTransaction.isVisible()){
            System.out.println(addTransaction.getDescription());
        }
        }
        catch(Exception ex){
            
        }
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnProject;
    private javax.swing.JButton btuAddTransaction;
    private javax.swing.JButton btunStatistics;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbAccountsSummary;
    // End of variables declaration//GEN-END:variables
}
